debug = true
app_name = "gin-template"
static_dir = "./static"
static_url = "http://localhost:8080/static"
listen = "0.0.0.0:3344"
log_dir = ""

[Mysql]
  host = "127.0.0.1"
  port = "3306"
  username = "root"
  password = "123456"
  data_base = "springboot3"

[Sqlite]
  base_path = "D:\\work\\go\\template\\sever\\gin-template\\static\\db"
  sqlite_encryption_key = "2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D99"

[Redis]
  host = "0.0.0.0"
  port = 6379
  password = ""
  db = 0
  pool_size = 20
  pool_timeout = 5

[Logger]
  level = "debug"
  file_path = "D:\\work\\go\\template\\sever\\gin-template\\static\\logs\\app"
  max_age = "720h0m0s"
  rotation_time = "24h0m0s"

[Upload]
  file_path = "D:\\work\\go\\template\\sever\\gin-template\\static\\uploads"

[Ns]
  host = "0.0.0.0"
  port = 8848
  grpc_port = 9848
  context_path = "/nacos"
  username = "nacos"
  password = "123456"
  group_name = "DEFAULT_GROUP"
  namespaceId = "nacos-namespace-id"
  dataId = "nacos-dataId"
  log_dir = "D:\\work\\go\\template\\sever\\gin-template\\static\\nacos\\log"
  cache_dir = "D:\\work\\go\\template\\sever\\gin-template\\static\\nacos\\cache"
  not_load_cache_as_start = true
  rotate_time = "24h"
  max_age = 30
  max_size = 100
  log_level = "info"
  timeout_ms = 500
  update_cache_when_empty = true
  max_backups = 30
  compress = true
  local_time = true
