Debug = true
StaticDir = "./static"
StaticUrl = "http://localhost:8080/static"
Listen = "0.0.0.0:3344"
LogDir = ""
Host = "127.0.0.1"
Port = "3306"
Username = "root"
Password = "123456"
DataBase = "springboot3"
Level = "debug"
FilePath = "static/logs/app"
MaxAge = "720h0m0s"
RotationTime = "24h0m0s"
UploadPath = "static/uploads"
