// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/insert": {
            "post": {
                "description": "配置 描述",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "创建 配置",
                "parameters": [
                    {
                        "description": "配置结构体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ConfigEntity"
                        }
                    }
                }
            }
        },
        "/config/insertMany": {
            "post": {
                "description": "批量配置 描述",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "批量创建 配置",
                "parameters": [
                    {
                        "description": "配置结构体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigsDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.ConfigEntity"
                            }
                        }
                    }
                }
            }
        },
        "/ws/broadcast": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "广播 WebSocket 消息",
                "parameters": [
                    {
                        "description": "消息体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BroadcastRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/count": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "获取当前 WebSocket 连接数",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.WsClientCountResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BroadcastRequest": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "hello"
                }
            }
        },
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "dial udp: ..."
                },
                "error": {
                    "type": "string",
                    "example": "需要字段 msg"
                }
            }
        },
        "controller.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "controller.WsClientCountResponse": {
            "type": "object",
            "properties": {
                "client_count": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "dto.ConfigDTO": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "name": {
                    "description": "使用 example 提供示例值",
                    "type": "string",
                    "example": "name-张三"
                },
                "value": {
                    "type": "string",
                    "example": "value-张三"
                }
            }
        },
        "dto.ConfigsDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ConfigDTO"
                    }
                }
            }
        },
        "entity.ConfigEntity": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "时间字段，使用 datetime(3) 以支持毫秒精度",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "软删除字段，使用指针，允许为 NULL",
                    "type": "string"
                },
                "id": {
                    "description": "主键，类型为 bigint unsigned，自增",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
